### ISSUE TITLE
installing cron config

### ISSUE THREAD

**Issue by LeoK80** [mjanser/ansible-role-mysql#8]
I've been seeing some issues/errors running this role when it comes to `ensure cron job is installed` from cron.yml https://github.com/mjanser/ansible-role-mysql/blob/dcfe8b0dc6997066c406eb5e129a29ee6b9b6a88/tasks/backup/cron.yml#L6

according to ansible docs when you use `cron_file` you also need specify `user` (which I found in `backup.ncf.j2` to be called `backup`). Which would make it look more like this:

```
- name: ensure cron job is installed
  cron:
    name: MySQL/MariaDB backup
    cron_file: mysql-backup
    user: backup
    special_time: daily
    job: /usr/local/bin/mysql-backup
```

Just thought to mention it. Cheers.
